### ISSUE TITLE
setTimeout 인자가 표준과 다름

### ISSUE THREAD

**Issue by saroro1** [VioletXF/MessengerBot#17]
`표준 구현`

![20220118_033819.jpg](https://user-images.githubusercontent.com/46727085/149823074-b3063818-faaf-4721-91ce-f2be252c3fba.jpg)

`메봇 구현`
![20220118_034017.jpg](https://user-images.githubusercontent.com/46727085/149823109-227f1758-1688-40c2-bc81-31c5696a4346.jpg)
![Screenshot_20220118-033953_MessengerBot.jpg](https://user-images.githubusercontent.com/46727085/149823116-5469a2cb-3cbe-4a0e-a19c-34fba91955c9.jpg)

setTimeout(func, delay,arg1....)인데 메봇에서는 setTimeout(func, delay, [arg1,...]) 이리 구현 되어있습니다

**Comment by naijun0403** [comment]
최신 업스트림에서 타이머관련 코드가 재작성되었습니다.

```javascript
const bot = BotManager.getCurrentBot();

function t(a, b) {
  Log.d(a)
  Log.d(b)
}

function test(msg) {
  setTimeout(t, 2000, 3, 5);
}

function onMessage(msg) {
  if (msg.content === "/test") {
    test(msg)
  }
}

bot.addListener(Event.MESSAGE, onMessage)
```

다음 스크립트 작동시 이제
![image](https://github.com/user-attachments/assets/e6e09c3e-d165-420f-ad41-df96c48a4464)
다음과 같이 정상작동하므로, 이슈를 닫겠습니다 :smile:
