### ISSUE TITLE
clearInterval(clearTimeout) 표준 미구현

### ISSUE THREAD

**Issue by ghost** [VioletXF/MessengerBot#19]
유효하지 않은 TimeoutID를 인자로 주면 표준과는 다르게 예외가 발생합니다.
## 오류내용
```js
clearTimeout(103);
```
```
Runtime Error(test1)
Wrapped java.lang.IndexOutOfBoundsException: Index: 102, Size: 0 (test1#2)	at test1:2
```
## 표준
> Passing an invalid ID to clearTimeout() silently does nothing; no exception is thrown.
clearTimeout()에 잘못된 ID를 전달하면 아무 작업도 수행되지 않습니다. 즉, 예외가 발생하지 않습니다.
[MDN](https://developer.mozilla.org/en-US/docs/Web/API/clearTimeout)

**Comment by naijun0403** [comment]
최신 업스트림에서 timer 관련 함수들이 재구현됨에 따라 더이상 잘못된 id는 문제를 일으키지 않습니다.

0.7.36a 릴리즈부터 적용됩니다.

문제가 해결되었으니 해당 이슈를 close하겠습니다.
